### ISSUE TITLE
Feature image to fill a certain dimension 

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#14]
Please set the image so that if the thumbnail image is not the same aspect ratio, to automatically fill the dimension. 
![screen shot 2014-10-08 at 2 51 51 pm](https://cloud.githubusercontent.com/assets/9021120/4565995/97acae86-4f24-11e4-8e4f-8b68ad3e3762.png)

**Comment by matt-cook** [comment]
thumbnails are all 4:3. let me know if you want a different ratio.
