### ISSUE TITLE
Markdown generator to not use -- in url

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#16]
Check for double "-" in URL, example:
http://magnified-joy.github.io/magnifiedjoy.com/personal/travelingjoy-site-launch-giveaway--kickstarter-calendar--adventure--airstream/

**Comment by matt-cook** [comment]
that's what I get for live editing without testing. should be fixed now

**Comment by matt-cook** [comment]
will need to modify filenames of existing posts if they were created with this issue
