### ISSUE TITLE
Unable to use # in title or label

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#17]
Looks like when I use # in a title, it will comment out the line.
If i use escape as documented in Markdown # it should produce #, however it shows up as # 

Here's the tile and label in markdown file
title: Magnified Joy site launch #travelingjoy giveaway | kickstarter calendar | adventure | airstream 
label: Site Launch #travelingjoy giveaway

Here's the result http://magnified-joy.github.io/magnifiedjoy.com/personal/travelingjoy-site-launch-giveaway-kickstarter-calendar-adventure-airstream/

![screen shot 2014-10-09 at 6 11 45 pm](https://cloud.githubusercontent.com/assets/9021120/4585669/af674122-5009-11e4-825f-b8a5b80c31d2.png)
![screen shot 2014-10-09 at 6 11 35 pm](https://cloud.githubusercontent.com/assets/9021120/4585670/af67c160-5009-11e4-93b2-e98cd4f579bc.png)

**Comment by matt-cook** [comment]
there may be another solution, but the easiest way is to just use HTML character codes:

http://www.ascii.cl/htmlcodes.htm

So instead of `#` you can write `&#35;`
