### ISSUE TITLE
Mobile: responsive resize of portfolio base on screen width? 

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#18]
In portrait mode of iphone is bad, in landscape mode of iphone is tollerable but photo still getting cut off sometimes. Can we have it fit to width of screen? I'm open to suggestions too.

![image](https://cloud.githubusercontent.com/assets/9021120/4586785/32cea4b0-501e-11e4-9e9f-c0e4075aa64a.png)
![image](https://cloud.githubusercontent.com/assets/9021120/4586787/37c652ba-501e-11e4-9e89-df3a0749dc4d.png)

**Comment by magnifiedjoy** [comment]
I think it works 99% of the time in landscape, once in a while when going from portrait to landscape it freaks out like this: (the couple is supposed to be centered to the page)
![img_7079](https://cloud.githubusercontent.com/assets/9021120/4586797/80dd3be4-501e-11e4-8fe1-980d77320366.PNG)

But 99% of time it's doing this (which is fine):
![img_7004](https://cloud.githubusercontent.com/assets/9021120/4586807/b1c090f8-501e-11e4-945e-ed1337f3ad24.png)

**Comment by magnifiedjoy** [comment]
on the homepage landscape photo in portrait mode is center weighted.
![img_0102](https://cloud.githubusercontent.com/assets/9021120/4586828/0ce8e1e2-501f-11e4-8307-355cba5c32ec.png)

**Comment by matt-cook** [comment]
Homepage is easy, since it has a set height and scales to cover.. unfortunately scaling to fit height without cropping at most resolutions, then scaling to fit width if it overflows at low res is much trickier. looking into it.

**Comment by matt-cook** [comment]
not getting anywhere on this right now. it'll need to wait till tomorrow morning.

**Comment by magnifiedjoy** [comment]
No worries, not a major bug.

**Comment by magnifiedjoy** [comment]
Something happened? 

—
