### ISSUE TITLE
Pictures in reviews are too large when in portrait mode of iPad

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#2]
Under the rave section when I had my iPad in portrait the pictures were full width of the screen and looked a bit grainy, when I put it in landscape mode they were smaller and looked fine.

**Comment by magnifiedjoy** [comment]
![image](https://cloud.githubusercontent.com/assets/9021120/4564414/683b31a2-4f17-11e4-8829-fb553b4b5991.png)
Screen shot from iPad on portrait mode.

Make the (portrait orientation) page look like what you would see on the computer/landscape mode as well.

**Comment by matt-cook** [comment]
fixed by 38eed4d5013b3dcc672a37d39e9ba4ef0208d0dc and f15c25e321a2ac2a9ca3eb3f8267b84a18cf51cf
