### ISSUE TITLE
Need to put in place a 404 handler

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#27]

**Comment by matt-cook** [comment]
Done. Not checked into github. Example:

http://weddings.magnifiedjoy.com/wedding/waukesha-wi-traditional-hmong-wedding-cross-cultural-hmong-american-wedding-pakou-matt/

**Comment by magnifiedjoy** [comment]
More robust 404 handler for page that for real does not exist.

**Comment by magnifiedjoy** [comment]
ie: www.magnifiedjoy.com/example404error

Getting the following:

404
There isn't a GitHub Page here.

Are you trying to publish one? It may take up to ten minutes until your page is available.

Read the full documentation to learn how to set up GitHub Pages
for your repository, organization, or user account.

**Comment by matt-cook** [comment]
Will do. Straightforward: https://help.github.com/articles/custom-404-pages/

**Comment by matt-cook** [comment]
You can edit the copy in 404.html
