### ISSUE TITLE
Switch nameservers away from Host Gator

### ISSUE THREAD

**Issue by matt-cook** [magnified-joy/magnifiedjoy.com#28]
Should use GoDaddy directly or another DNS provider, so the old hosting account can be shut down in the future.

**Comment by matt-cook** [comment]
I suppose this isn't mandatory, just a good idea in the long run.

**Comment by magnifiedjoy** [comment]
I've copied all image files to Google Drive and updated all the posts to the correct Google Drive Links. There should not be any need to point to the old server. Please change NS on Godaddy to point directly github

**Comment by magnifiedjoy** [comment]
When switching DNS, please make sure MX records are updated on Godaddy as our emails are dependent on the MX record to point to googleapps.
