### ISSUE TITLE
hover and click issue with categories page with iPad

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#3]
Some of the blog posts when I tried to select them didn't take me to the post. (issue with hover and entering into blog post)

**Comment by matt-cook** [comment]
having trouble reproducing this one here on our ipad. want to bring yours tonight? or any other details on what you did when it didn't work?

**Comment by magnifiedjoy** [comment]
Yep, will bring ipad and laptop tonight. —

**Comment by magnifiedjoy** [comment]
![img_5375](https://cloud.githubusercontent.com/assets/9021120/4583790/090ae36a-4ff5-11e4-9a22-be505fa774d2.png)

**Comment by matt-cook** [comment]
Can you test this? It should be fixed by e02a86b45507554d4bc2c5db21d8dea39f827ac4
