### ISSUE TITLE
Expected behavior for carousel?

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#33]
Seems inconsistent when you land on page sometimes it will start flipping through carousel. Sometimes it will just pause there and not auto advance. Sometimes when you click on the next arrow key it will advance, but it will follow by the auto advance, which result in two advances.

**Comment by matt-cook** [comment]
Should it auto-advance or no?

**Comment by magnifiedjoy** [comment]
It should auto advance, but it seems to pause auto advance if your cursor is over any part of the carousel. Maybe usability wise, it should pause auto advance if the cursor is on the actual button, but not pause auto-advance when it's just on the carousel.

I don't know what the expected behavior is, so not sure if its behaving properly.
