### ISSUE TITLE
Open Graph image in header?

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#35]
Right now there is not a whole lot for Open Graph to pull from, should probably define an image so that it's not pulling from one of the social media icons.

https://developers.facebook.com/tools/debug/og/object/

![screen shot 2014-10-10 at 4 08 37 pm](https://cloud.githubusercontent.com/assets/9021120/4599086/d3ee3a6a-50c1-11e4-9d93-178a42952dc7.png)

**Comment by magnifiedjoy** [comment]
Can use the following picture for og:image
https://googledrive.com/host/0B2YHeCssXjxzN0UzdVZtNmFINTQ/magnifiedjoy-opengraph.jpg

**Comment by matt-cook** [comment]
posts and pages with "thumbnail" or "image" specified will show these instead of the default image.
