### ISSUE TITLE
Help with CSS to format in page subscribe form

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#41]
On the kick starter page, the CSS I had in the markdown file is a fixed width. Looks good on desktop but messes up on Mobile. 

Please help format the field so that it's about 80% of the width of the column.

![img_7966](https://cloud.githubusercontent.com/assets/9021120/4696343/5feabf92-57e4-11e4-825b-f2377ff05eb6.png)

**Comment by matt-cook** [comment]
You can use `{% include subscribe.html %}` now, anywhere you need to drop in the form.
