### ISSUE TITLE
weddings.magnifiedjoy.com DNS error

### ISSUE THREAD

**Issue by magnifiedjoy** [magnified-joy/magnifiedjoy.com#46]
Looks like the redirect broke, probably when we switched DNS to cloudflare killed off old server.

**Comment by matt-cook** [comment]
Fixed: http://weddings.magnifiedjoy.com. Cloudflare is your new DNS provider, so any subdomains need to be set up through their admin page: https://www.cloudflare.com/dns-settings?z=magnifiedjoy.com and then in this case I added a rule to redirect: https://www.cloudflare.com/page-rules?z=magnifiedjoy.com
